//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Core.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Core.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to words_{0}.
        /// </summary>
        internal static string WORDS_DICTIONARY_NAME_FORMAT {
            get {
                return ResourceManager.GetString("WORDS_DICTIONARY_NAME_FORMAT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AA
        ///AAH
        ///AAHED
        ///AAHING
        ///AAHS
        ///AAL
        ///AALII
        ///AALIIS
        ///AALS
        ///AARDVARK
        ///AARDVARKS
        ///AARDWOLF
        ///AARDWOLVES
        ///AARGH
        ///AARRGH
        ///AARRGHH
        ///AARTI
        ///AARTIS
        ///AAS
        ///AASVOGEL
        ///AASVOGELS
        ///AB
        ///ABA
        ///ABAC
        ///ABACA
        ///ABACAS
        ///ABACI
        ///ABACK
        ///ABACS
        ///ABACTERIAL
        ///ABACTINAL
        ///ABACTINALLY
        ///ABACTOR
        ///ABACTORS
        ///ABACUS
        ///ABACUSES
        ///ABAFT
        ///ABAKA
        ///ABAKAS
        ///ABALONE
        ///ABALONES
        ///ABAMP
        ///ABAMPERE
        ///ABAMPERES
        ///ABAMPS
        ///ABAND
        ///ABANDED
        ///ABANDING
        ///ABANDON
        ///ABANDONED
        ///ABANDONEDLY
        ///ABANDONEE
        ///ABANDONEES
        ///ABANDONER
        ///ABANDONERS
        ///ABANDONING
        ///ABANDONMENT
        ///ABANDONMENTS
        ///ABANDONS
        ///ABANDONWARE
        ///ABANDONWARES
        ///ABANDS
        ///ABAPICAL
        ///ABAS
        ///ABASE
        /// [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string words_en {
            get {
                return ResourceManager.GetString("words_en", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to a
        ///aba
        ///abaá
        ///ababillarse
        ///ababol
        ///abacá
        ///abacal
        ///abacalera
        ///abacalero
        ///abacera
        ///abacería
        ///abacero
        ///abacial
        ///ábaco
        ///abacora
        ///abacorar
        ///abad
        ///abada
        ///abadejo
        ///abadenga
        ///abadengo
        ///abadernar
        ///abadesa
        ///abadí
        ///abadía
        ///abadiado
        ///abadiato
        ///ab aeterno
        ///abajadero
        ///abajamiento
        ///abajar
        ///abajeña
        ///abajeño
        ///abajera
        ///abajo
        ///abakuá
        ///abalada
        ///abalanzar
        ///abalaustrada
        ///abalaustrado
        ///abalconada
        ///abalconado
        ///abaldonar
        ///abalear
        ///abaleo
        ///abalizar
        ///aballar
        ///aballestar
        ///abalorio
        ///abaluartar
        ///abanador
        ///abanar
        ///abancalar
        ///abanda
        ///abanderada
        ///abanderado
        ///abanderamiento
        ///abanderar
        ///abanderizar [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string words_es {
            get {
                return ResourceManager.GetString("words_es", resourceCulture);
            }
        }
    }
}
