//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class Player
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Player()
        {
            this.Avatar = 0;
            this.Games = 0;
            this.Wins = 0;
            this.Verified = false;
        }
    
        public int UserId { get; set; }
        public string Nickname { get; set; }
        public string Password { get; set; }
        public short Avatar { get; set; }
        public string Email { get; set; }
        public System.DateTime Registered { get; set; }
        public int Games { get; set; }
        public int Wins { get; set; }
        public string VerificationCode { get; set; }
        public bool Verified { get; set; }
    }
}
