//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ScrabbleEntities : DbContext
    {
        public ScrabbleEntities()
            : base("name=ScrabbleEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Friendship> friendships { get; set; }
        public virtual DbSet<gameResults> gameResults { get; set; }
        public virtual DbSet<games> games { get; set; }
        public virtual DbSet<Player> players { get; set; }
        public virtual DbSet<settings> settings { get; set; }
    }
}
