//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProyectoV1
{
    using System;
    using System.Collections.Generic;
    
    public partial class games
    {
        public int idGame { get; set; }
        public int duration { get; set; }
        public System.DateTime date { get; set; }
        public int idWinner { get; set; }
    }
}
