//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProyectoV1
{
    using System;
    using System.Collections.Generic;
    
    public partial class settings
    {
        public int idSettings { get; set; }
        public int playerId { get; set; }
        public string lenguege { get; set; }
        public Nullable<int> videoResolutionWidth { get; set; }
        public Nullable<int> videoResolutionHeigth { get; set; }
        public string videoStyle { get; set; }
        public Nullable<int> audioMaster { get; set; }
        public Nullable<int> audioMusic { get; set; }
        public Nullable<int> audioEffects { get; set; }
    }
}
