//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Client.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Client.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Accept.
        /// </summary>
        public static string COMMON_ACCEPT_BUTTON {
            get {
                return ResourceManager.GetString("COMMON_ACCEPT_BUTTON", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back.
        /// </summary>
        public static string COMMON_BACK_BUTTON {
            get {
                return ResourceManager.GetString("COMMON_BACK_BUTTON", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string COMMON_CANCEL_BUTTON {
            get {
                return ResourceManager.GetString("COMMON_CANCEL_BUTTON", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EMAIL.
        /// </summary>
        public static string COMMON_EMAIL_LABEL {
            get {
                return ResourceManager.GetString("COMMON_EMAIL_LABEL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Empty.
        /// </summary>
        public static string COMMON_EMPTY {
            get {
                return ResourceManager.GetString("COMMON_EMPTY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Friends.
        /// </summary>
        public static string COMMON_FRIENDS {
            get {
                return ResourceManager.GetString("COMMON_FRIENDS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid characters.
        /// </summary>
        public static string COMMON_INVALID_CHARACTERS_LABEL {
            get {
                return ResourceManager.GetString("COMMON_INVALID_CHARACTERS_LABEL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading....
        /// </summary>
        public static string COMMON_LOADING {
            get {
                return ResourceManager.GetString("COMMON_LOADING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NICKNAME.
        /// </summary>
        public static string COMMON_NICKNAME_LABEL {
            get {
                return ResourceManager.GetString("COMMON_NICKNAME_LABEL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PASSWORD.
        /// </summary>
        public static string COMMON_PASSWORD_LABEL {
            get {
                return ResourceManager.GetString("COMMON_PASSWORD_LABEL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reject.
        /// </summary>
        public static string COMMON_REJECT_BUTTON {
            get {
                return ResourceManager.GetString("COMMON_REJECT_BUTTON", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Required*.
        /// </summary>
        public static string COMMON_REQUIRED_LABEL {
            get {
                return ResourceManager.GetString("COMMON_REQUIRED_LABEL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown Error :(.
        /// </summary>
        public static string COMMON_UNKNOWN_ERROR {
            get {
                return ResourceManager.GetString("COMMON_UNKNOWN_ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ➕ Add.
        /// </summary>
        public static string FRIENDS_LIST_ADD_BUTTON {
            get {
                return ResourceManager.GetString("FRIENDS_LIST_ADD_BUTTON", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are already friends!.
        /// </summary>
        public static string FRIENDS_LIST_FRIEND_REQUEST_ALREADY_FRIENDS {
            get {
                return ResourceManager.GetString("FRIENDS_LIST_FRIEND_REQUEST_ALREADY_FRIENDS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you going to send a request to yourself?.
        /// </summary>
        public static string FRIENDS_LIST_FRIEND_REQUEST_AUTOREQUEST {
            get {
                return ResourceManager.GetString("FRIENDS_LIST_FRIEND_REQUEST_AUTOREQUEST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You already have a pending friend request!.
        /// </summary>
        public static string FRIENDS_LIST_FRIEND_REQUEST_PENDING {
            get {
                return ResourceManager.GetString("FRIENDS_LIST_FRIEND_REQUEST_PENDING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Player does not exists!.
        /// </summary>
        public static string FRIENDS_LIST_FRIEND_REQUEST_PLAYER_DOES_NOT_EXISTS {
            get {
                return ResourceManager.GetString("FRIENDS_LIST_FRIEND_REQUEST_PLAYER_DOES_NOT_EXISTS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Friend request sent!.
        /// </summary>
        public static string FRIENDS_LIST_FRIEND_REQUEST_SUCCESS {
            get {
                return ResourceManager.GetString("FRIENDS_LIST_FRIEND_REQUEST_SUCCESS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Friends list.
        /// </summary>
        public static string FRIENDS_LIST_HEADER {
            get {
                return ResourceManager.GetString("FRIENDS_LIST_HEADER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to In game.
        /// </summary>
        public static string FRIENDS_LIST_STATUS_IN_GAME {
            get {
                return ResourceManager.GetString("FRIENDS_LIST_STATUS_IN_GAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Offline.
        /// </summary>
        public static string FRIENDS_LIST_STATUS_OFFLINE {
            get {
                return ResourceManager.GetString("FRIENDS_LIST_STATUS_OFFLINE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Online.
        /// </summary>
        public static string FRIENDS_LIST_STATUS_ONLINE {
            get {
                return ResourceManager.GetString("FRIENDS_LIST_STATUS_ONLINE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pending.
        /// </summary>
        public static string FRIENDS_LIST_STATUS_PENDING {
            get {
                return ResourceManager.GetString("FRIENDS_LIST_STATUS_PENDING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Incorrect password.
        /// </summary>
        public static string LOGIN_INCORRECT_PASSWORD_MESSAGE {
            get {
                return ResourceManager.GetString("LOGIN_INCORRECT_PASSWORD_MESSAGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid credentials.
        /// </summary>
        public static string LOGIN_INVALID_CREDENTIALS_MESSAGE {
            get {
                return ResourceManager.GetString("LOGIN_INVALID_CREDENTIALS_MESSAGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log in to Scrabble.
        /// </summary>
        public static string LOGIN_MENU_HEADER {
            get {
                return ResourceManager.GetString("LOGIN_MENU_HEADER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log in.
        /// </summary>
        public static string LOGIN_MENU_LOGIN_BUTTON {
            get {
                return ResourceManager.GetString("LOGIN_MENU_LOGIN_BUTTON", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign up.
        /// </summary>
        public static string LOGIN_MENU_REGISTER_BUTTON {
            get {
                return ResourceManager.GetString("LOGIN_MENU_REGISTER_BUTTON", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EXIT.
        /// </summary>
        public static string MAIN_MENU_EXIT_BUTTON {
            get {
                return ResourceManager.GetString("MAIN_MENU_EXIT_BUTTON", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PLAY.
        /// </summary>
        public static string MAIN_MENU_PLAY_BUTTON {
            get {
                return ResourceManager.GetString("MAIN_MENU_PLAY_BUTTON", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SETTINGS.
        /// </summary>
        public static string MAIN_MENU_SETTINGS_BUTTON {
            get {
                return ResourceManager.GetString("MAIN_MENU_SETTINGS_BUTTON", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} is now the party leader.
        /// </summary>
        public static string PARTY_CHAT_LEADER_TRANSFER_MESSAGE_FORMAT {
            get {
                return ResourceManager.GetString("PARTY_CHAT_LEADER_TRANSFER_MESSAGE_FORMAT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}: {1}.
        /// </summary>
        public static string PARTY_CHAT_MESSAGE_FORMAT {
            get {
                return ResourceManager.GetString("PARTY_CHAT_MESSAGE_FORMAT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} has joined the party..
        /// </summary>
        public static string PARTY_CHAT_PLAYER_JOIN_MESSAGE_FORMAT {
            get {
                return ResourceManager.GetString("PARTY_CHAT_PLAYER_JOIN_MESSAGE_FORMAT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} left the party..
        /// </summary>
        public static string PARTY_CHAT_PLAYER_LEAVE_MESSAGE_FORMAT {
            get {
                return ResourceManager.GetString("PARTY_CHAT_PLAYER_LEAVE_MESSAGE_FORMAT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} -&gt; You: {1}.
        /// </summary>
        public static string PARTY_CHAT_WHISPER_FORMAT {
            get {
                return ResourceManager.GetString("PARTY_CHAT_WHISPER_FORMAT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to End turn.
        /// </summary>
        public static string PARTY_GAME_END_TURN_BUTTON {
            get {
                return ResourceManager.GetString("PARTY_GAME_END_TURN_BUTTON", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pass.
        /// </summary>
        public static string PARTY_GAME_PASS_BUTTON {
            get {
                return ResourceManager.GetString("PARTY_GAME_PASS_BUTTON", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} invited you to play!.
        /// </summary>
        public static string PARTY_INVITATION_TEXT {
            get {
                return ResourceManager.GetString("PARTY_INVITATION_TEXT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type something....
        /// </summary>
        public static string PARTY_LOBBY_CHAT_INPUT_WATERMARK {
            get {
                return ResourceManager.GetString("PARTY_LOBBY_CHAT_INPUT_WATERMARK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CHAT.
        /// </summary>
        public static string PARTY_LOBBY_CHAT_LABEL {
            get {
                return ResourceManager.GetString("PARTY_LOBBY_CHAT_LABEL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FRIENDS.
        /// </summary>
        public static string PARTY_LOBBY_FRIENDS_LABEL {
            get {
                return ResourceManager.GetString("PARTY_LOBBY_FRIENDS_LABEL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Game language: .
        /// </summary>
        public static string PARTY_LOBBY_GAME_LANGUAGE_LABEL {
            get {
                return ResourceManager.GetString("PARTY_LOBBY_GAME_LANGUAGE_LABEL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GROUP.
        /// </summary>
        public static string PARTY_LOBBY_GROUP_LABEL {
            get {
                return ResourceManager.GetString("PARTY_LOBBY_GROUP_LABEL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PARTY LOBBY.
        /// </summary>
        public static string PARTY_LOBBY_HEADER {
            get {
                return ResourceManager.GetString("PARTY_LOBBY_HEADER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Leader.
        /// </summary>
        public static string PARTY_LOBBY_LEADER_LABEL {
            get {
                return ResourceManager.GetString("PARTY_LOBBY_LEADER_LABEL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your lobby code is: .
        /// </summary>
        public static string PARTY_LOBBY_LOBBY_CODE_LABEL {
            get {
                return ResourceManager.GetString("PARTY_LOBBY_LOBBY_CODE_LABEL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start game.
        /// </summary>
        public static string PARTY_LOBBY_START_GAME_BUTTON {
            get {
                return ResourceManager.GetString("PARTY_LOBBY_START_GAME_BUTTON", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time limit: .
        /// </summary>
        public static string PARTY_LOBBY_TIME_LIMIT_LABEL {
            get {
                return ResourceManager.GetString("PARTY_LOBBY_TIME_LIMIT_LABEL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back.
        /// </summary>
        public static string PLAY_MENU_BACK_BUTTON {
            get {
                return ResourceManager.GetString("PLAY_MENU_BACK_BUTTON", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Join Game.
        /// </summary>
        public static string PLAY_MENU_JOIN_GAME_BUTTON {
            get {
                return ResourceManager.GetString("PLAY_MENU_JOIN_GAME_BUTTON", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New game.
        /// </summary>
        public static string PLAY_MENU_NEW_GAME_BUTTON {
            get {
                return ResourceManager.GetString("PLAY_MENU_NEW_GAME_BUTTON", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ✏ Edit.
        /// </summary>
        public static string PLAYER_PROFILE_EDIT_BUTTON {
            get {
                return ResourceManager.GetString("PLAYER_PROFILE_EDIT_BUTTON", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Player profile.
        /// </summary>
        public static string PLAYER_PROFILE_HEADER {
            get {
                return ResourceManager.GetString("PLAYER_PROFILE_HEADER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /Assets/images/avatars/default_{0}.png.
        /// </summary>
        public static string PROFILE_AVATAR_FILE_PATH_FORMAT {
            get {
                return ResourceManager.GetString("PROFILE_AVATAR_FILE_PATH_FORMAT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Games played: .
        /// </summary>
        public static string PROFILE_PROFILE_GAMES_COUNT_LABEL {
            get {
                return ResourceManager.GetString("PROFILE_PROFILE_GAMES_COUNT_LABEL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registered: .
        /// </summary>
        public static string PROFILE_PROFILE_REGISTERED_LABEL {
            get {
                return ResourceManager.GetString("PROFILE_PROFILE_REGISTERED_LABEL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Games won: .
        /// </summary>
        public static string PROFILE_PROFILE_WINS_COUNT_LABEL {
            get {
                return ResourceManager.GetString("PROFILE_PROFILE_WINS_COUNT_LABEL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CONFIRM PASSWORD.
        /// </summary>
        public static string SIGN_UP_CONFIRM_PASSWORD_LABEL {
            get {
                return ResourceManager.GetString("SIGN_UP_CONFIRM_PASSWORD_LABEL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign up for Scrabble.
        /// </summary>
        public static string SIGN_UP_HEADER {
            get {
                return ResourceManager.GetString("SIGN_UP_HEADER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid email.
        /// </summary>
        public static string SIGN_UP_INVALID_EMAIL_LABEL {
            get {
                return ResourceManager.GetString("SIGN_UP_INVALID_EMAIL_LABEL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User already exists.
        /// </summary>
        public static string SIGN_UP_USER_ALREADY_EXISTS_MESSAGE {
            get {
                return ResourceManager.GetString("SIGN_UP_USER_ALREADY_EXISTS_MESSAGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email too long!.
        /// </summary>
        public static string SIGNUP_EMAIL_TOO_LONG {
            get {
                return ResourceManager.GetString("SIGNUP_EMAIL_TOO_LONG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nickname too long!.
        /// </summary>
        public static string SIGNUP_NICKNAME_TOO_LONG {
            get {
                return ResourceManager.GetString("SIGNUP_NICKNAME_TOO_LONG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password too long!.
        /// </summary>
        public static string SIGNUP_PASSWORD_TOO_LONG {
            get {
                return ResourceManager.GetString("SIGNUP_PASSWORD_TOO_LONG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Passwords do not match.
        /// </summary>
        public static string SIGNUP_PASSWORDS_DO_NOT_MATCH_LABEL {
            get {
                return ResourceManager.GetString("SIGNUP_PASSWORDS_DO_NOT_MATCH_LABEL", resourceCulture);
            }
        }
    }
}
