//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Client.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Client.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back.
        /// </summary>
        public static string buttonBack {
            get {
                return ResourceManager.GetString("buttonBack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CANCEL.
        /// </summary>
        public static string buttonCancelSignUp {
            get {
                return ResourceManager.GetString("buttonCancelSignUp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LOGIN.
        /// </summary>
        public static string buttonLogin {
            get {
                return ResourceManager.GetString("buttonLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        public static string buttonOkSignUp {
            get {
                return ResourceManager.GetString("buttonOkSignUp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SIGN UP.
        /// </summary>
        public static string buttonSignUp {
            get {
                return ResourceManager.GetString("buttonSignUp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chat.
        /// </summary>
        public static string chatLabel {
            get {
                return ResourceManager.GetString("chatLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Users.
        /// </summary>
        public static string chatUsersLabel {
            get {
                return ResourceManager.GetString("chatUsersLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Empty.
        /// </summary>
        public static string COMMON_EMPTY {
            get {
                return ResourceManager.GetString("COMMON_EMPTY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Friends.
        /// </summary>
        public static string COMMON_FRIENDS {
            get {
                return ResourceManager.GetString("COMMON_FRIENDS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading....
        /// </summary>
        public static string COMMON_LOADING {
            get {
                return ResourceManager.GetString("COMMON_LOADING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to USER.
        /// </summary>
        public static string COMMON_NICKNAME_LABEL {
            get {
                return ResourceManager.GetString("COMMON_NICKNAME_LABEL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PASSWORD.
        /// </summary>
        public static string COMMON_PASSWORD_LABEL {
            get {
                return ResourceManager.GetString("COMMON_PASSWORD_LABEL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Required*.
        /// </summary>
        public static string COMMON_REQUIRED_LABEL {
            get {
                return ResourceManager.GetString("COMMON_REQUIRED_LABEL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EMAIL.
        /// </summary>
        public static string emailSignUp {
            get {
                return ResourceManager.GetString("emailSignUp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Incorrect password.
        /// </summary>
        public static string incorrectPassword {
            get {
                return ResourceManager.GetString("incorrectPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid credentials.
        /// </summary>
        public static string invalidCredentials {
            get {
                return ResourceManager.GetString("invalidCredentials", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading....
        /// </summary>
        public static string loadingLabel {
            get {
                return ResourceManager.GetString("loadingLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LOGIN.
        /// </summary>
        public static string Login {
            get {
                return ResourceManager.GetString("Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log in to Scrabble.
        /// </summary>
        public static string LOGIN_MENU_HEADER {
            get {
                return ResourceManager.GetString("LOGIN_MENU_HEADER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log in.
        /// </summary>
        public static string LOGIN_MENU_LOGIN_BUTTON {
            get {
                return ResourceManager.GetString("LOGIN_MENU_LOGIN_BUTTON", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign up.
        /// </summary>
        public static string LOGIN_MENU_REGISTER_BUTTON {
            get {
                return ResourceManager.GetString("LOGIN_MENU_REGISTER_BUTTON", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EXIT.
        /// </summary>
        public static string MAIN_MENU_EXIT_BUTTON {
            get {
                return ResourceManager.GetString("MAIN_MENU_EXIT_BUTTON", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PLAY.
        /// </summary>
        public static string MAIN_MENU_PLAY_BUTTON {
            get {
                return ResourceManager.GetString("MAIN_MENU_PLAY_BUTTON", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SETTINGS.
        /// </summary>
        public static string MAIN_MENU_SETTINGS_BUTTON {
            get {
                return ResourceManager.GetString("MAIN_MENU_SETTINGS_BUTTON", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NAME.
        /// </summary>
        public static string nameSignUp {
            get {
                return ResourceManager.GetString("nameSignUp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NEWUSER.
        /// </summary>
        public static string NewUser {
            get {
                return ResourceManager.GetString("NewUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NICKNAME.
        /// </summary>
        public static string nicknameSignUp {
            get {
                return ResourceManager.GetString("nicknameSignUp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send.
        /// </summary>
        public static string sendButton {
            get {
                return ResourceManager.GetString("sendButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign up.
        /// </summary>
        public static string titleSignUp {
            get {
                return ResourceManager.GetString("titleSignUp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown error.
        /// </summary>
        public static string unknownError {
            get {
                return ResourceManager.GetString("unknownError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknow user.
        /// </summary>
        public static string unknowUserLogin {
            get {
                return ResourceManager.GetString("unknowUserLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User already exists.
        /// </summary>
        public static string userAlreadyExists {
            get {
                return ResourceManager.GetString("userAlreadyExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} has entered the chat!.
        /// </summary>
        public static string userJoinChatMessageFormat {
            get {
                return ResourceManager.GetString("userJoinChatMessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} just leave the chat.
        /// </summary>
        public static string userLeaveChatMessageFormat {
            get {
                return ResourceManager.GetString("userLeaveChatMessageFormat", resourceCulture);
            }
        }
    }
}
